### ISSUE TITLE
trouble with bcwallet for python<3, >=2.7 (issue with pip)

### ISSUE THREAD

**Issue by ShaunHoyes** [blockcypher/bcwallet#36]
When I run the following command, I'm running into permission issues:

```
pip install bcwallet
```
So I ran this instead:
```
pip3 install bcwallet
```
When doing this, I get the following error message:

```
Could not find a version that satisfies the requirement python<3,>=2.7 (from bcwallet) (from versions: )
No matching distribution found for python<3,>=2.7 (from bcwallet)
```

I'm using a Mac, El Capitan.

**Comment by mflaxman** [comment]
Sorry about that @ShaunHoyes and thanks for the bug report.

Can you try installing with python2?: 
`pip2 install bcwallet`

I've had some problems with forcing python version 2 on OSX since El Cap came out. That's certainly not a helpful error message :(

**Comment by ShaunHoyes** [comment]
Thanks @mflaxman 

After trying
```
pip2 install bcwallet
```
I got the following:
```
DEPRECATION: Uninstalling a distutils installed project (six) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling six-1.4.1:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-8.1.1-py2.7.egg/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-8.1.1-py2.7.egg/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-8.1.1-py2.7.egg/pip/req/req_set.py", line 726, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip-8.1.1-py2.7.egg/pip/req/req_install.py", line 746, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip-8.1.1-py2.7.egg/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip-8.1.1-py2.7.egg/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/var/folders/c4/xrzlmzws1h370r3pj057d13w0000gn/T/pip-bZdJet-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'
```

**Comment by mflaxman** [comment]
Thanks @ShaunHoyes !

Hmm, that seems tricky.

Can you try?:
`pip2 install bcwallet --ignore-installed six`

Sorry, I would just do it on my machine but something about the config on mine is different and I don't get the error you're getting.

Thanks.

I think this open issue with pip and el cap is the problem IYC:
https://github.com/pypa/pip/issues/3165

**Comment by ShaunHoyes** [comment]
I still get that same error message:
```
Could not find a version that satisfies the requirement python<3,>=2.7 (from bcwallet) (from versions: )
No matching distribution found for python<3,>=2.7 (from bcwallet)
```

I see the ongoing, unresolved issue. Definitely seems like a Capitan issue. I will try doing it on another machine.

Thanks

**Comment by mflaxman** [comment]
Thanks @ShaunHoyes  and sorry for the trouble :(

How about this?:
```python2 pip install blockcypher```

If that doesn't work, try appending `--ignore-installed six` at the end.

**Comment by ShaunHoyes** [comment]
After trying it both ways, I get the same message:
```
/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'pip': [Errno 2] No such file or directory
```

**Comment by mflaxman** [comment]
Aaaaah, sorry @ShaunHoyes :(

One last idea. I didn't want to suggest this because it's an ugly solution.

What about adding `sudo` to the front of those commands (starting at the beginning of the thread and working down to the most recent if necessary).

**Comment by ShaunHoyes** [comment]
It's the same situation even with the ```sudo```.

**Comment by mflaxman** [comment]
Fail! Sorry @ShaunHoyes :(

Do you have python2 installed at all? Do you get anything if you type this:
` which python2 `

**Comment by ShaunHoyes** [comment]
With ```which python2```, I get ```/Library/Frameworks/Python.framework/Versions/2.7/bin/python2```

I downloaded the Python 3.5.1 package a few days ago, but I haven't used the command line with it. Could that be the issue here? Would I have to delete the Python 3.5?

**Comment by mflaxman** [comment]
Hmmmm, sorry @ShaunHoyes I'm not sure what's going on :(

I wish I could duplicate your environment.

My hope is that something is messed up about your python installation, I'd bet if you re-install python/pip it will work. I'm going to leave this open and see if anyone else says this is happening for them, too.

**Comment by ShaunHoyes** [comment]
I'm getting the same error message when I try to uninstall. There's definitely something wrong on my side. How should I go about uninstalling the pip/python package?

**Comment by ShaunHoyes** [comment]
The version I'm currently using is pip 8.1.1

**Comment by mflaxman** [comment]
Which error? Usually `$ pip uninstall packagenamehere` works fine.

Note that in some circumstances you may need to specify `pip2` or `pip3` and in some crazy edge case you may need to `sudo` first.

**Comment by ShaunHoyes** [comment]
Silly question: how do I find the package name?

**Comment by mflaxman** [comment]
Not 100% sure what you're asking, try `$ pip freeze`.

**Comment by ShaunHoyes** [comment]
I factory reset my computer, and started fresh. The ```pip install bcwallet``` worked and I was able to download it. There must have been a problem with something I installed previously. 

I think this issue is solved for me. Sorry for the inconvenience. 

Thanks

**Comment by mflaxman** [comment]
Glad you got it working!

I'll mark this as closed for now.
