### ISSUE TITLE
v1.2.6 crash when dumping addresses only

### ISSUE THREAD

**Issue by dooglus** [blockcypher/bcwallet#37]
I just heard about bcwallet, was trying it out using an xpub of mine and got it to crash:

    $ bcwallet --wallet=xpub$xpub

    Welcome to bcwallet!

    Here's what makes bcwallet unique:
      -Multi-Currency: Supports Bitcoin (and Testnet), Litecoin, Dogecoin, and BlockCypher Testnet.
      -Nearly Trustless: Keys and signatures are generated locally for trustless use.
      -No Key Pool: The seed is not stored locally, the app is booted with the user supplying the master key so the filesystem is never used.
      -Hard to Mess Up: As long as you don't lose or share your master private key, everything else is simple.
      -Accurate Transaction Fees: Smart calculation lets user decide how long until their transaction will make it into a block.
      -Airgap Usage: Can be booted with the public key in watch-only mode, which is great for fetching transaction info to sign offline with a more secure machine.
      -Very Few LoC: Blockchain heavy lifting powered by BlockCypher, which leads to massive reduction in client-side code used for ease of auditing.

    You've opened your HD wallet in PUBLIC key mode, so you CANNOT sign transactions.
    To sign transactions, open your HD wallet in private key mode like this:

        $ bcwallet --wallet=xprv...
        
    ----------------------------------------------------------------------

    Balance: 67,664,636.07 bits
    Transactions: 6

    More info:
    https://live.blockcypher.com/btc/xpub/xpub[...]/?subchain-indices=0-1

    ----------------------------------------------------------------------

    What do you want to do?:
      1: Show balance and transactions
      2: Show new receiving addresses
      3: Send funds (more options here)
      0: Dump addresses (advanced users only)
      
      q: Quit bcwallet
      
    ฿ [1]: 0
    Which addresses do you want?
      1: Active - have funds to spend
      2: Spent - no funds to spend (because they have been spent)
      3: Unused - no funds to spend (because the address has never been used)
      0: All (works offline) - regardless of whether they have funds to spend (super advanced users only)
      
      b: Go Back
      
    ฿ [1]: 1
    Displaying Public Addresses Only
    For Private Keys, please open bcwallet with your Master Private Key:

        $ bcwallet --wallet=xprv123...
        

    Receiving Address Chain - m/0/k:
    path (address/wif)

    Bad Robot!
    Quitting on Unexpected Error:
    'wif'
      'wif'

    Here are the details to share with the developer for a bug report: 

      Traceback (most recent call last):
        File "/usr/local/lib/python2.7/dist-packages/bcwallet/bcwallet.py", line 1366, in invoke_cli
          cli()
        File "/usr/local/lib/python2.7/dist-packages/bcwallet/bcwallet.py", line 1266, in cli
          return wallet_home(wallet_obj)
        File "/usr/local/lib/python2.7/dist-packages/bcwallet/bcwallet.py", line 1173, in wallet_home
          dump_private_keys_or_addrs_chooser(wallet_obj=wallet_obj)
        File "/usr/local/lib/python2.7/dist-packages/bcwallet/bcwallet.py", line 1028, in dump_private_keys_or_addrs_chooser
          return dump_selected_keys_or_addrs(wallet_obj=wallet_obj, zero_balance=False, used=True)
        File "/usr/local/lib/python2.7/dist-packages/bcwallet/bcwallet.py", line 983, in dump_selected_keys_or_addrs
          wif=address_obj['wif'],
      KeyError: 'wif'
      

    User private keys intentionally never saved.
    Please do not lose your seed, bcwallet intentionally has no backup!

    $

**Comment by mflaxman** [comment]
@dooglus sorry for that and thanks for the bug report!

I was able to duplicate the issue and will update bcwallet today. I'll let you know here when I do.

Note that if you dump all addresses by selecting option 0 > 0 > y that will work, it's just breaking on dumping subsets of addresses (in public mode only).

Thanks again.

**Comment by mflaxman** [comment]
Hi @dooglus, this is now fixed and pushed to pypi (https://pypi.python.org/pypi/bcwallet/1.2.7). Note that it sometimes can take a few minutes for the latest version to be available in pypi for download via pip.

When you boot bcwallet, it will prompt you to upgrade like this:

```
$ pip install --upgrade bcwallet 
```

Sorry about that, and thanks again for the bug report!
