### ISSUE TITLE
Client Side Verification Fail

### ISSUE THREAD

**Issue by rcs1000** [blockcypher/bcwallet#41]
Hi,

I am unable to either dump private keys or send bitcoin, as I get a Client Side Verification Fail whenever I try.

Does anyone have any idea why that might happen?

Thanks
Robert

**Comment by quentinlesceller** [comment]
Hi, @rcs1000. Thank you for the issue. I haven't seen this issue in a while so I'm going to close it. Feel free to reopen if it happens again.
